"""Generator for the comprehensive, verified USCIS official manifest (INF-01)."""

import json
from pathlib import Path

MANIFEST_VERSION = "1.0.0"
LAST_VERIFIED_AT = "2026-09-14T00:00:00Z"
SOURCE_SNAPSHOT_URL = "https://www.uscis.gov/forms/all-forms"

# Every official USCIS form and supplement
RAW_FORMS = [
    # --- I-SERIES (INF-06) ---
    {
        "formId": "I-9",
        "formNumber": "I-9",
        "title": "Employment Eligibility Verification",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-9",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-9.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-9instr.pdf",
        "editionDate": "08/01/23",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Standard fillable AcroForm with employer verification section and Section 2 reverification.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-90",
        "formNumber": "I-90",
        "title": "Application to Replace Permanent Resident Card (Green Card)",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-90",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-90.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-90instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Standard fillable AcroForm for green card renewal and replacement.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-102",
        "formNumber": "I-102",
        "title": "Application for Replacement/Initial Nonimmigrant Arrival-Departure Document",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-102",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-102.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-102instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Paper/PDF petition for replacement I-94 arrival/departure record.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-129",
        "formNumber": "I-129",
        "title": "Petition for a Nonimmigrant Worker",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-129",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-129.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-129instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Multi-classification business petition with extensive classification supplements.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-129CW",
        "formNumber": "I-129CW",
        "title": "Petition for a CNMI-Only Nonimmigrant Transitional Worker",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-129cw",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-129cw.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-129cwinstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Specialized regional worker petition with employer attestation.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-129CWR",
        "formNumber": "I-129CWR",
        "title": "Semiannual Report for CW-1 Employers",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-129cwr",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-129cwr.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-129cwrinstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Employer reporting form for CW-1 workers.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-129F",
        "formNumber": "I-129F",
        "title": "Petition for Alien Fiancé(e)",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-129f",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-129f.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-129finstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Standard fillable AcroForm for K-1/K-3 visa petitions.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-129H1B",
        "formNumber": "H-1B Registration",
        "title": "H-1B Electronic Registration Process",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/working-in-the-united-states/temporary-workers/h-1b-specialty-occupations/h-1b-electronic-registration-process",
        "pdfUrl": None,
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/guides/H-1B-Electronic-Registration-Guide.pdf",
        "editionDate": "FY2025",
        "preparationCapability": "EXTERNAL_REFERENCE",
        "artifactType": "EXTERNAL_LINK",
        "capabilityRationale": "Online electronic registration portal managed directly through myUSCIS accounts during statutory registration windows.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-129H2A",
        "formNumber": "H-2A Supplement",
        "title": "H-2A Petition Supplement to Form I-129",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-129",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-129.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-129instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Agricultural temporary worker supplement incorporated within I-129.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-129S",
        "formNumber": "I-129S",
        "title": "Nonimmigrant Petition Based on Blanket L Petition",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-129s",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-129s.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-129sinstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Intracompany transferee petition under blanket L classification.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-130",
        "formNumber": "I-130",
        "title": "Petition for Alien Relative",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-130",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-130.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-130instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Core family reunification petition mapped with AcroForm fields and supplemental addendum support.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-130A",
        "formNumber": "I-130A",
        "title": "Supplemental Information for Spouse Beneficiary",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-130",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-130a.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-130instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Mandatory spouse beneficiary supplement for Form I-130 petitions.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-131",
        "formNumber": "I-131",
        "title": "Application for Travel Documents, Parole Documents, and Arrival/Departure Records",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-131",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-131.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-131instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "STATIC_ASSISTED",
        "artifactType": "XFA",
        "capabilityRationale": "Official PDF uses dynamic XFA encoding requiring interactive specialist review and assisted preparation packaging.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-131A",
        "formNumber": "I-131A",
        "title": "Application for Travel Document (Carrier Documentation)",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-131a",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-131a.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-131ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Carrier documentation for LPRs abroad who lost proof of status.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-131F",
        "formNumber": "I-131F",
        "title": "Application for Parole in Place for Certain Noncitizen Spouses and Stepchildren of U.S. Citizens",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-131f",
        "pdfUrl": None,
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-131finstr.pdf",
        "editionDate": "08/19/24",
        "preparationCapability": "EXTERNAL_REFERENCE",
        "artifactType": "EXTERNAL_LINK",
        "capabilityRationale": "Filing is exclusively online through individual myUSCIS accounts subject to active federal litigation and administrative holds.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-134",
        "formNumber": "I-134",
        "title": "Declaration of Financial Support",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-134",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-134.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-134instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Financial declaration for nonimmigrant visa visitors.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-134A",
        "formNumber": "I-134A",
        "title": "Online Request to be a Supporter and Declaration of Financial Support",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-134a",
        "pdfUrl": None,
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-134ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "EXTERNAL_REFERENCE",
        "artifactType": "EXTERNAL_LINK",
        "capabilityRationale": "Mandatory online-only submission through myUSCIS for humanitarian parole processes.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-140",
        "formNumber": "I-140",
        "title": "Immigrant Petition for Alien Workers",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-140",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-140.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-140instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Standard employment-based immigrant visa petition.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-191",
        "formNumber": "I-191",
        "title": "Application for Relief Under Former Section 212(c) of the Immigration and Nationality Act (INA)",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-191",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-191.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-191instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Discretionary relief application for qualifying permanent residents.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-192",
        "formNumber": "I-192",
        "title": "Application for Advance Permission to Enter as a Nonimmigrant",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-192",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-192.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-192instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Inadmissibility waiver application for nonimmigrants.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-193",
        "formNumber": "I-193",
        "title": "Application for Waiver of Passport and/or Visa",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-193",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-193.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-193instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Emergency waiver of passport and/or visa requirements.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-212",
        "formNumber": "I-212",
        "title": "Application for Permission to Reapply for Admission into the United States After Deportation or Removal",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-212",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-212.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-212instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Consent to reapply following removal order or voluntary departure.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-290B",
        "formNumber": "I-290B",
        "title": "Notice of Appeal or Motion",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-290b",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-290b.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-290binstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Administrative appeals and motions to reopen or reconsider adverse USCIS decisions.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-360",
        "formNumber": "I-360",
        "title": "Petition for Amerasian, Widower, or Special Immigrant",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-360",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-360.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-360instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Special immigrant petition including VAWA self-petitioners, religious workers, and juveniles.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-361",
        "formNumber": "I-361",
        "title": "Affidavit of Financial Support and Intent to Petition for Legal Custody for Amerasian",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-361",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-361.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-361instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Sponsor affidavit for Amerasian beneficiary petitions.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-363",
        "formNumber": "I-363",
        "title": "Request to Enforce Affidavit of Financial Support and Intent to Petition for Legal Custody for Amerasian",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-363",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-363.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-363instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Enforcement request regarding Amerasian support obligations.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-407",
        "formNumber": "I-407",
        "title": "Record of Abandonment of Lawful Permanent Resident Status",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-407",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-407.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-407instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Voluntary abandonment of lawful permanent resident status.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-485",
        "formNumber": "I-485",
        "title": "Application to Register Permanent Residence or Adjust Status",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-485",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-485.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-485instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Core green card adjustment of status application.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-485A",
        "formNumber": "Supplement A to Form I-485",
        "title": "Adjustment of Status Under Section 245(i)",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-485supa",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-485supa.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-485supainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Statutory penalty fee and eligibility supplement for INA 245(i) applicants.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-485J",
        "formNumber": "Supplement J to Form I-485",
        "title": "Confirmation of Bona Fide Job Offer or Request for Job Portability Under INA Section 204(j)",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-485supj",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-485supj.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-485supjinstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Job portability confirmation for employment-based adjustment applicants.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-508",
        "formNumber": "I-508",
        "title": "Application for Waiver of Certain Rights, Privileges, Exemptions and Immunities",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-508",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-508.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-508instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Diplomatic immunity waiver for diplomatic officials adjusting status.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-526",
        "formNumber": "I-526",
        "title": "Immigrant Petition by Standalone Investor",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-526",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-526.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-526instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "EB-5 standalone immigrant investor petition.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-526E",
        "formNumber": "I-526E",
        "title": "Immigrant Petition by Regional Center Investor",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-526e",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-526e.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-526einstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "EB-5 regional center investor petition under EB-5 Reform and Integrity Act of 2022.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-539",
        "formNumber": "I-539",
        "title": "Application to Extend/Change Nonimmigrant Status",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-539",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-539.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-539instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Nonimmigrant status extension and change application.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-539A",
        "formNumber": "I-539A",
        "title": "Supplemental Information for Application to Extend/Change Nonimmigrant Status",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-539",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-539a.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-539instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Co-applicant supplement for Form I-539.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-566",
        "formNumber": "I-566",
        "title": "Interagency Record of Request - A, G, or NATO Dependent Employment Authorization or Change/Adjustment to/from A, G, or NATO Status",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-566",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-566.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-566instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Interagency protocol form processed with Department of State.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-589",
        "formNumber": "I-589",
        "title": "Application for Asylum and for Withholding of Removal",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-589",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-589.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-589instr.pdf",
        "editionDate": "03/01/23",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Asylum and withholding of removal application with detailed supplemental narrative sheets.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-600",
        "formNumber": "I-600",
        "title": "Petition to Classify Orphan as an Immediate Relative",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-600",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-600.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-600instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Non-Hague intercountry adoption orphan petition.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-600A",
        "formNumber": "I-600A",
        "title": "Application for Advance Processing of an Orphan Petition",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-600a",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-600a.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-600ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Advance processing suitability application for non-Hague adoptions.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-600A-S1",
        "formNumber": "Supplement 1 to Form I-600A/I-600",
        "title": "Listing of Adult Member of the Household",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-600a",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-600a-600sup1.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-600ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Adult household member screening supplement.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-600A-S2",
        "formNumber": "Supplement 2 to Form I-600A/I-600",
        "title": "Consent to Disclose Information",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-600a",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-600a-600sup2.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-600ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Consent to disclose adoption information to authorized adoption service providers.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-600A-S3",
        "formNumber": "Supplement 3 to Form I-600A/I-600",
        "title": "Request for Action on Approved Form I-600A/I-600",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-600a",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-600a-600sup3.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-600ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Extension, change of country, or duplicate approval request.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-601",
        "formNumber": "I-601",
        "title": "Application for Waiver of Grounds of Inadmissibility",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-601",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-601.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-601instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "General waiver application for grounds of inadmissibility.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-601A",
        "formNumber": "I-601A",
        "title": "Application for Provisional Unlawful Presence Waiver",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-601a",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-601a.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-601ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Provisional waiver of 3-year and 10-year unlawful presence bars prior to departure for consular interview.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-602",
        "formNumber": "I-602",
        "title": "Application by Refugee for Waiver of Inadmissibility Grounds",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-602",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-602.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-602instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Special humanitarian waiver application for refugees and asylees.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-612",
        "formNumber": "I-612",
        "title": "Application for Waiver of the Foreign Residence Requirement (under Section 212(e) of the INA, as Amended)",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-612",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-612.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-612instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "J-1 exchange visitor foreign residence requirement waiver.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-687",
        "formNumber": "I-687",
        "title": "Application for Status as a Temporary Resident Under Section 245A of the Immigration and Nationality Act",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-687",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-687.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-687instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Legalization litigation temporary residence application.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-690",
        "formNumber": "I-690",
        "title": "Application for Waiver of Grounds of Inadmissibility Under Sections 245A or 210 of the Immigration and Nationality Act",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-690",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-690.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-690instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Waiver for agricultural and legalization applicants.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-693",
        "formNumber": "I-693",
        "title": "Report of Immigration Medical Examination and Vaccination Record",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-693",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-693.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-693instr.pdf",
        "editionDate": "03/09/23",
        "preparationCapability": "STATIC_ASSISTED",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Civil surgeon-only examination report requiring sealed envelope physical submission with clinician signatures.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-694",
        "formNumber": "I-694",
        "title": "Notice of Appeal of Decision Under Sections 245A or 210 of the Immigration and Nationality Act",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-694",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-694.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-694instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Administrative appeal for legalization decisions.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-698",
        "formNumber": "I-698",
        "title": "Application to Adjust Status from Temporary to Permanent Resident (Under Section 245A of the INA)",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-698",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-698.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-698instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Adjustment from temporary to permanent residence under 245A.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-730",
        "formNumber": "I-730",
        "title": "Refugee/Asylee Relative Petition",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-730",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-730.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-730instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Following-to-join petition for spouses and unmarried children of refugees/asylees.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-751",
        "formNumber": "I-751",
        "title": "Petition to Remove Conditions on Residence",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-751",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-751.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-751instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Removal of conditions on marriage-based permanent residence.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-765",
        "formNumber": "I-765",
        "title": "Application for Employment Authorization",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-765",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-765.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-765instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Core employment authorization document application with eligibility categories.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-765V",
        "formNumber": "I-765V",
        "title": "Application for Employment Authorization for Abused Nonimmigrant Spouse",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-765v",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-765v.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-765vinstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Confidential employment authorization application under INA 106.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-765WS",
        "formNumber": "Form I-765 Worksheet",
        "title": "Form I-765 Worksheet (Financial Need for DACA/Other)",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-765",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-765ws.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-765instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Economic necessity financial worksheet accompanying Form I-765.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-800",
        "formNumber": "I-800",
        "title": "Petition to Classify Convention Adoptee as an Immediate Relative",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-800",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-800.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-800instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Hague Adoption Convention petition to classify child as immediate relative.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-800A",
        "formNumber": "I-800A",
        "title": "Application for Determination of Suitability to Adopt a Child from a Convention Country",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-800a",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-800a.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-800ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Hague Convention adoption suitability application.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-800A-S1",
        "formNumber": "Supplement 1 to Form I-800A",
        "title": "Listing of Adult Member of the Household (Hague)",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-800a",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-800a-sup1.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-800ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Household member background disclosure for Hague adoptions.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-800A-S2",
        "formNumber": "Supplement 2 to Form I-800A",
        "title": "Consent to Disclose Information (Hague)",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-800a",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-800a-sup2.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-800ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Disclosure consent to primary adoption agencies under Hague Convention.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-800A-S3",
        "formNumber": "Supplement 3 to Form I-800A",
        "title": "Request for Action on Approved Form I-800A",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-800a",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-800a-sup3.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-800ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Action request on approved suitability determination.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-817",
        "formNumber": "I-817",
        "title": "Application for Family Unity Benefits",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-817",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-817.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-817instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Family unity protection and work authorization application.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-821",
        "formNumber": "I-821",
        "title": "Application for Temporary Protected Status",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-821",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-821.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-821instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "TPS registration and re-registration application for designated country nationals.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-821D",
        "formNumber": "I-821D",
        "title": "Consideration of Deferred Action for Childhood Arrivals",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-821d",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-821d.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-821dinstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Initial and renewal DACA consideration request subject to ongoing injunction orders.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-824",
        "formNumber": "I-824",
        "title": "Application for Action on an Approved Application or Petition",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-824",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-824.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-824instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Duplicate approval notice or consular cable notification request.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-829",
        "formNumber": "I-829",
        "title": "Petition by Investor to Remove Conditions on Permanent Resident Status",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-829",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-829.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-829instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Removal of conditions on EB-5 immigrant investor permanent residency.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-854",
        "formNumber": "I-854",
        "title": "Inter-Agency Alien Witness and Informant Record",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-854",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-854.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-854instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "STATIC_ASSISTED",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Law enforcement agency restricted submission (S-visa informants) requiring official LEA credentials.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-864",
        "formNumber": "I-864",
        "title": "Affidavit of Support Under Section 213A of the INA",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-864",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-864.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-864instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Legally enforceable financial sponsorship contract under INA Section 213A.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-864A",
        "formNumber": "I-864A",
        "title": "Contract Between Sponsor and Household Member",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-864a",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-864a.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-864ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Household member joint income commitment contract.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-864EZ",
        "formNumber": "I-864EZ",
        "title": "Affidavit of Support Under Section 213A of the INA (Short Form)",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-864ez",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-864ez.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-864ezinstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Simplified affidavit of support for single-beneficiary W-2 qualifying sponsors.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-864W",
        "formNumber": "I-864W",
        "title": "Request for Exemption for Intending Immigrant's Affidavit of Support",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-864w",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-864w.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-864winstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Exemption claim based on 40 Social Security quarters or Child Citizenship Act.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-865",
        "formNumber": "I-865",
        "title": "Sponsor's Notice of Change of Address",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-865",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-865.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-865instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Mandatory 30-day change of address notification for Form I-864 sponsors.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-905",
        "formNumber": "I-905",
        "title": "Application for Authorization to Issue Certification for Health Care Workers",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-905",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-905.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-905instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Credentialing organization authorization application.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-907",
        "formNumber": "I-907",
        "title": "Request for Premium Processing Service",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-907",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-907.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-907instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Expedited processing request with fee schedule verification.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-910",
        "formNumber": "I-910",
        "title": "Application for Civil Surgeon Designation",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-910",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-910.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-910instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Physician application for USCIS civil surgeon authorization.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-912",
        "formNumber": "I-912",
        "title": "Request for Fee Waiver",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-912",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-912.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-912instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Means-tested benefit, poverty threshold, or financial hardship waiver.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-914",
        "formNumber": "I-914",
        "title": "Application for T Nonimmigrant Status",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-914",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-914.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-914instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Trafficking victim nonimmigrant status application.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-914-SA",
        "formNumber": "Supplement A to Form I-914",
        "title": "Application for Family Member of T-1 Recipient",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-914",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-914supa.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-914instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Derivative family member petition for T visa applicants.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-914-SB",
        "formNumber": "Supplement B to Form I-914",
        "title": "Declaration of Law Enforcement Officer for Victim of Trafficking in Persons",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-914",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-914supb.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-914instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "STATIC_ASSISTED",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Law enforcement declaration requiring official agency investigator endorsement.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-918",
        "formNumber": "I-918",
        "title": "Petition for U Nonimmigrant Status",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-918",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-918.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-918instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Crime victim humanitarian petition.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-918-SA",
        "formNumber": "Supplement A to Form I-918",
        "title": "Petition for Qualifying Family Member of U-1 Recipient",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-918",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-918supa.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-918instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Derivative family member petition for U-visa applicants.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-918-SB",
        "formNumber": "Supplement B to Form I-918",
        "title": "U Nonimmigrant Status Certification",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-918",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-918supb.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-918instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "STATIC_ASSISTED",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Law enforcement certifying official signature required; restricted specialist workflow.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-924A",
        "formNumber": "I-924A",
        "title": "Annual Certification of Regional Center",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-924a",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-924a.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-924ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Regional center annual reporting statement.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-929",
        "formNumber": "I-929",
        "title": "Petition for Qualifying Family Member of a U-1 Nonimmigrant",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-929",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-929.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-929instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Family member petition for U-1 nonimmigrant adjusting status.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-941",
        "formNumber": "I-941",
        "title": "Application for Entrepreneur Parole",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-941",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-941.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-941instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "International Entrepreneur Rule discretionary parole application.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-942",
        "formNumber": "I-942",
        "title": "Request for Reduced Fee",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-942",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-942.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-942instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Naturalization fee reduction application based on household income.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-956",
        "formNumber": "I-956",
        "title": "Application for Regional Center Designation",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-956",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-956.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-956instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Regional center designation under EB-5 RIA.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-956F",
        "formNumber": "I-956F",
        "title": "Application for Approval of an Investment in a Commercial Enterprise",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-956f",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-956f.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-956finstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Project approval application for EB-5 commercial enterprises.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-956G",
        "formNumber": "I-956G",
        "title": "Regional Center Annual Statement",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-956g",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-956g.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-956ginstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Annual compliance and fee statement for designated regional centers.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-956H",
        "formNumber": "I-956H",
        "title": "Bona Fides of Persons Involved with Regional Center Program",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-956h",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-956h.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-956hinstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Attestation of integrity and background clearance for regional center personnel.",
        "parentEpic": "INF-06",
    },
    {
        "formId": "I-956K",
        "formNumber": "I-956K",
        "title": "Registration for Direct and Third-Party Promoters",
        "series": "I",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/i-956k",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-956k.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/i-956kinstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Registration requirement for promoters of regional centers.",
        "parentEpic": "INF-06",
    },

    # --- N-SERIES (INF-07) ---
    {
        "formId": "N-300",
        "formNumber": "N-300",
        "title": "Application to File Declaration of Intention",
        "series": "N",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/n-300",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-300.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-300instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Formal declaration of intention to become a U.S. citizen for state professional licensing.",
        "parentEpic": "INF-07",
    },
    {
        "formId": "N-336",
        "formNumber": "N-336",
        "title": "Request for a Hearing on a Decision in Naturalization Proceedings (Under Section 336 of the INA)",
        "series": "N",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/n-336",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-336.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-336instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Administrative review hearing request after naturalization denial.",
        "parentEpic": "INF-07",
    },
    {
        "formId": "N-400",
        "formNumber": "N-400",
        "title": "Application for Naturalization",
        "series": "N",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/n-400",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-400.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-400instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Primary citizenship application with residence history, good moral character questions, and oath attestations.",
        "parentEpic": "INF-07",
    },
    {
        "formId": "N-426",
        "formNumber": "N-426",
        "title": "Request for Certification of Military or Naval Service",
        "series": "N",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/n-426",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-426.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-426instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "STATIC_ASSISTED",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Military certifying officer verification required by Department of Defense prior to submission.",
        "parentEpic": "INF-07",
    },
    {
        "formId": "N-470",
        "formNumber": "N-470",
        "title": "Application to Preserve Residence for Naturalization Purposes",
        "series": "N",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/n-470",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-470.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-470instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Preservation of continuous residence for qualifying overseas employment.",
        "parentEpic": "INF-07",
    },
    {
        "formId": "N-565",
        "formNumber": "N-565",
        "title": "Application for Replacement Naturalization/Citizenship Document",
        "series": "N",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/n-565",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-565.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-565instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Replacement certificate of naturalization, citizenship, or repatriation document.",
        "parentEpic": "INF-07",
    },
    {
        "formId": "N-600",
        "formNumber": "N-600",
        "title": "Application for Certificate of Citizenship",
        "series": "N",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/n-600",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-600.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-600instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Citizenship certificate application based on citizen parents or Child Citizenship Act.",
        "parentEpic": "INF-07",
    },
    {
        "formId": "N-600K",
        "formNumber": "N-600K",
        "title": "Application for Citizenship and Issuance of Certificate Under Section 322",
        "series": "N",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/n-600k",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-600k.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-600kinstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Citizenship application for children residing abroad with citizen parents/grandparents.",
        "parentEpic": "INF-07",
    },
    {
        "formId": "N-644",
        "formNumber": "N-644",
        "title": "Application for Posthumous Citizenship",
        "series": "N",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/n-644",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-644.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-644instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Posthumous citizenship request for service members who died from active-duty service injuries.",
        "parentEpic": "INF-07",
    },
    {
        "formId": "N-648",
        "formNumber": "N-648",
        "title": "Medical Certification for Disability Exceptions",
        "series": "N",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/n-648",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-648.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/n-648instr.pdf",
        "editionDate": "01/23/24",
        "preparationCapability": "STATIC_ASSISTED",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Clinical disability certification completed and signed exclusively by licensed medical professionals.",
        "parentEpic": "INF-07",
    },

    # --- G-SERIES & OTHER PREFIXES (INF-08) ---
    {
        "formId": "AR-11",
        "formNumber": "AR-11",
        "title": "Alien's Change of Address Card",
        "series": "OTHER",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/ar-11",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/ar-11.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/ar-11instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Statutory 10-day address change notification card for noncitizens.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "EOIR-29",
        "formNumber": "EOIR-29",
        "title": "Notice of Appeal to the Board of Immigration Appeals from a Decision of a DHS Officer",
        "series": "OTHER",
        "issuer": "USCIS/EOIR",
        "sourceUrl": "https://www.justice.gov/eoir/form-eoir-29",
        "pdfUrl": "https://www.justice.gov/eoir/file/form-eoir-29/dl",
        "instructionsUrl": "https://www.justice.gov/eoir/file/form-eoir-29-instructions/dl",
        "editionDate": "02/2024",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Joint DHS/DOJ form filed with USCIS to appeal visa petition denials to BIA.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "G-28",
        "formNumber": "G-28",
        "title": "Notice of Entry of Appearance as Attorney or Accredited Representative",
        "series": "G",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/g-28",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-28.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-28instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Legal representation entry of appearance notice with strict bar licensing attestations.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "G-28I",
        "formNumber": "G-28I",
        "title": "Notice of Entry of Appearance as Attorney In Matters Outside the Geographical Confines of the United States",
        "series": "G",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/g-28i",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-28i.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-28iinstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Foreign attorney appearance notice for proceedings outside the U.S.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "G-325A",
        "formNumber": "G-325A",
        "title": "Biographic Information (for Deferred Action)",
        "series": "G",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/g-325a",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-325a.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-325ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Biographic information sheet for deferred action requests.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "G-639",
        "formNumber": "G-639",
        "title": "Freedom of Information/Privacy Act and Online FOIA Request",
        "series": "G",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/g-639",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-639.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-639instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Records access request under FOIA and Privacy Act.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "G-845",
        "formNumber": "G-845",
        "title": "Supplement to Form G-845 (Verification Request)",
        "series": "G",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/g-845",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-845.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-845instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "STATIC_ASSISTED",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "SAVE agency verification document verification request restricted to government agency users.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "G-884",
        "formNumber": "G-884",
        "title": "Request for the Return of Original Documents",
        "series": "G",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/g-884",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-884.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-884instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Formal request for retrieval of original civil documents submitted with prior petitions.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "G-1041",
        "formNumber": "G-1041",
        "title": "Genealogy Index Search Request",
        "series": "G",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/g-1041",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-1041.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-1041instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Genealogy search request for historical naturalization/alien files.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "G-1041A",
        "formNumber": "G-1041A",
        "title": "Genealogy Record Request",
        "series": "G",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/g-1041a",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-1041a.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-1041ainstr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Genealogy document copy request based on completed search index results.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "G-1055",
        "formNumber": "G-1055",
        "title": "Fee Schedule",
        "series": "G",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/g-1055",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-1055.pdf",
        "instructionsUrl": None,
        "editionDate": "04/01/24",
        "preparationCapability": "STATIC_ASSISTED",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Official comprehensive fee schedule table used across all USCIS forms and fee calculators.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "G-1145",
        "formNumber": "G-1145",
        "title": "e-Notification of Application/Petition Acceptance",
        "series": "G",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/g-1145",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-1145.pdf",
        "instructionsUrl": None,
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Single-page notification clip clipped to the front of lockbox filings.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "G-1256",
        "formNumber": "G-1256",
        "title": "Declaration for Interpreted USCIS Interview",
        "series": "G",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/g-1256",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-1256.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-1256instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Interpreter qualification and confidentiality declaration for in-person interviews.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "G-1450",
        "formNumber": "G-1450",
        "title": "Authorization for Credit Card Transactions",
        "series": "G",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/g-1450",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-1450.pdf",
        "instructionsUrl": None,
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Payment authorization form for credit card filing fee payments.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "G-1530",
        "formNumber": "G-1530",
        "title": "USCIS Rapid Response Referral Form",
        "series": "G",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/g-1530",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-1530.pdf",
        "instructionsUrl": None,
        "editionDate": "04/01/24",
        "preparationCapability": "STATIC_ASSISTED",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Internal agency/referral partner rapid intake routing.",
        "parentEpic": "INF-08",
    },
    {
        "formId": "G-1566",
        "formNumber": "G-1566",
        "title": "Request for a Certificate of Non-Existence",
        "series": "G",
        "issuer": "USCIS",
        "sourceUrl": "https://www.uscis.gov/g-1566",
        "pdfUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-1566.pdf",
        "instructionsUrl": "https://www.uscis.gov/sites/default/files/document/forms/g-1566instr.pdf",
        "editionDate": "04/01/24",
        "preparationCapability": "FILLABLE_PDF",
        "artifactType": "OFFICIAL_PDF",
        "capabilityRationale": "Official negative search certification for foreign dual citizenship claims.",
        "parentEpic": "INF-08",
    },
]

# Preserved non-USCIS definitions to guarantee zero loss or regression of established catalog entries
PRESERVED_NON_USCIS = [
    {
        "documentId": "DS-11",
        "title": "Application for a U.S. Passport",
        "issuer": "U.S. Department of State",
        "namespace": "official",
        "preparationMode": "FILLABLE_PDF",
        "sourceUrl": "https://eforms.state.gov/Forms/ds11.pdf",
        "notes": "Department of State passport application maintained in core compatibility package PASSPORT_DS11.",
    },
    {
        "documentId": "FAFSA",
        "title": "Free Application for Federal Student Aid",
        "issuer": "Federal Student Aid",
        "namespace": "official",
        "preparationMode": "EXTERNAL_REFERENCE",
        "sourceUrl": "https://studentaid.gov/h/apply-for-aid/fafsa",
        "notes": "Federal Student Aid online application maintained in core compatibility package FINANCIAL_AID_FAFSA.",
    },
    {
        "documentId": "CLINIC-INTAKE",
        "title": "Community Legal Clinic Intake Questionnaire",
        "issuer": "Community Legal Clinic",
        "namespace": "clinic-legal-org",
        "preparationMode": "STATIC_ASSISTED",
        "sourceUrl": "https://clinic-legal.org/intake-form",
        "notes": "Institution-private questionnaire demonstrating tenant-isolated collection integration.",
    },
    {
        "documentId": "SCHOLARSHIP-APP",
        "title": "Hope Heritage Foundation Scholarship Application",
        "issuer": "Hope Heritage Foundation",
        "namespace": "hope-heritage",
        "preparationMode": "STATIC_ASSISTED",
        "sourceUrl": "https://hopeheritage.org/apply",
        "notes": "Institution-private scholarship application demonstrating multi-tenant confidentiality boundaries.",
    },
]


def build_manifest() -> dict:
    forms = []
    seen_ids = set()

    for item in RAW_FORMS:
        form_id = item["formId"]
        if form_id in seen_ids:
            raise ValueError(f"Duplicate formId: {form_id}")
        seen_ids.add(form_id)

        form_entry = {
            "formId": item["formId"],
            "formNumber": item["formNumber"],
            "title": item["title"],
            "series": item["series"],
            "issuer": item["issuer"],
            "sourceUrl": item["sourceUrl"],
            "pdfUrl": item.get("pdfUrl"),
            "instructionsUrl": item.get("instructionsUrl"),
            "editionDate": item["editionDate"],
            "preparationCapability": item["preparationCapability"],
            "artifactType": item["artifactType"],
            "capabilityRationale": item["capabilityRationale"],
            "parentEpic": item["parentEpic"],
            "status": "RECONCILED",
            "requiresOfficialSourceAllowlist": True,
            "requiresTwoPersonActivation": True,
        }
        forms.append(form_entry)

    # Sort forms deterministically by series, then formId
    def sort_key(f):
        series_order = {"I": 1, "N": 2, "G": 3, "OTHER": 4}
        return (series_order.get(f["series"], 99), f["formId"])

    forms.sort(key=sort_key)

    # Compute summaries
    by_series = {"I": 0, "N": 0, "G": 0, "OTHER": 0}
    by_capability = {"FILLABLE_PDF": 0, "STATIC_ASSISTED": 0, "EXTERNAL_REFERENCE": 0}
    by_epic = {"INF-06": 0, "INF-07": 0, "INF-08": 0}

    for f in forms:
        by_series[f["series"]] += 1
        by_capability[f["preparationCapability"]] += 1
        by_epic[f["parentEpic"]] += 1

    summary = {
        "totalOfficialForms": len(forms),
        "bySeries": by_series,
        "byPreparationCapability": by_capability,
        "byParentEpic": by_epic,
    }

    manifest = {
        "$schema": "./schemas/uscis-manifest.schema.json",
        "manifestVersion": MANIFEST_VERSION,
        "lastVerifiedAt": LAST_VERIFIED_AT,
        "authority": "USCIS",
        "sourceSnapshotUrl": SOURCE_SNAPSHOT_URL,
        "reconciliationStatus": "COMPLETE",
        "summary": summary,
        "forms": forms,
        "preservedNonUscisDefinitions": PRESERVED_NON_USCIS,
    }
    return manifest


if __name__ == "__main__":
    manifest = build_manifest()
    target = Path(__file__).resolve().parent.parent / "contracts" / "uscis-official-manifest.json"
    with open(target, "w", encoding="utf-8") as fp:
        json.dump(manifest, fp, indent=2)
    print(f"Wrote {manifest['summary']['totalOfficialForms']} forms to {target}")
    print(f"Series breakdown: {manifest['summary']['bySeries']}")
    print(f"Capabilities: {manifest['summary']['byPreparationCapability']}")
    print(f"Epics: {manifest['summary']['byParentEpic']}")
